# SECTION 2: CREATING ARRAYS - THE FOUNDATION


## Basic list to array conversion

In [128]:
import numpy as np

In [129]:
list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)
print("From list:", array_from_list)
print("Type:", type(array_from_list))
print("Shape:", array_from_list.shape)
print("Data type:", array_from_list.dtype)

From list: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Shape: (5,)
Data type: int64


In [130]:
# 2D list to array
list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_2d = np.array(list_2d)
print("\n2D array:\n", array_2d)
print("Shape:", array_2d.shape)


2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


## 2. CREATING ARRAYS WITH SPECIFIC DATA TYPES

Float array

In [131]:
# Float array
float_array = np.array([1, 2, 3, 4], dtype=np.float64)
print("Float array:", float_array)
print("Data type:", float_array.dtype)

Float array: [1. 2. 3. 4.]
Data type: float64


Integer array

In [132]:
int_array = np.array([1.1, 2.2, 3.3], dtype=np.int32)
print("Int array:", int_array)
print("Data type:", int_array.dtype)

Int array: [1 2 3]
Data type: int32


Complex array

In [133]:
complex_array = np.array([1 + 2j, 3 + 4j, 5 + 6j])
print("Complex array:", complex_array)
print("Data type:", complex_array.dtype)

Complex array: [1.+2.j 3.+4.j 5.+6.j]
Data type: complex128


# 3. CREATING ARRAYS WITH BUILT-IN FUNCTIONS


In [134]:
# Zeros array
zeros_array = np.zeros(5)
print("Zeros:", zeros_array)

# Ones array
ones_array = np.ones((3, 4))
print("Ones shape (3,4):\n", ones_array)

# Empty array (uninitialized memory)
empty_array = np.empty((2, 3))
print("Empty shape (2,3):\n", empty_array)

# Full array (fill with specific value)
full_array = np.full((2, 2), 7)
print("Full array with value 7:\n", full_array)

Zeros: [0. 0. 0. 0. 0.]
Ones shape (3,4):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Empty shape (2,3):
 [[1. 2. 3.]
 [4. 5. 6.]]
Full array with value 7:
 [[7 7]
 [7 7]]


# 4. CREATING ARRAYS WITH ARANGE AND LINSPACE

### arange - similar to range() but returns array

In [135]:
range_array = np.arange(0, 10, 2)  # start, stop, step
range_array

array([0, 2, 4, 6, 8])

### linspace - creates evenly spaced numbers

In [136]:
linspace_array = np.linspace(0, 1, 5)  # start, stop, num_points
linspace_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### logspace - creates logarithmically spaced numbers

In [137]:
logspace_array = np.logspace(0, 3, 4)  # 10^0 to 10^3, 4 points
logspace_array

array([   1.,   10.,  100., 1000.])

# 5. CREATING IDENTITY AND DIAGONAL MATRICES

In [138]:
# Identity matrix
identity_matrix = np.eye(3)
print("Identity matrix:\n", identity_matrix)

# Diagonal matrix
diagonal_matrix = np.diag([1, 2, 3, 4])
print("Diagonal matrix:\n", diagonal_matrix)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Diagonal matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# 6. CREATING RANDOM ARRAYS

Set seed for reproducibility for random numbers generation
if you set the seed to 42, you will get the same random numbers every time you run the code.
if you don't set the seed, you will get different random numbers every time you run the code.



In [139]:
x=np.random.seed(42)

# Random integers
random_ints = np.random.randint(1, 11, 5)
print("Random integers (1-10):", random_ints)

# Random floats
random_floats = np.random.random(5)
print("Random floats (0-1):", random_floats)

# Random normal distribution
random_normal = np.random.normal(0, 1, 5)
print("Random normal distribution:", random_normal)

Random integers (1-10): [7 4 8 5 7]
Random floats (0-1): [0.44583275 0.09997492 0.45924889 0.33370861 0.14286682]
Random normal distribution: [-0.4826188   0.16416482  0.23309524  0.11799461  1.46237812]


# 7. CREATING ARRAYS WITH MESHGRID

In [140]:
# Create coordinate grids
x = np.linspace(0, 2, 3)
y = np.linspace(0, 2, 3)
X, Y = np.meshgrid(x, y)
print("X grid:\n", X)
print("Y grid:\n", Y)

X grid:
 [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
Y grid:
 [[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]]


# 8. CREATING ARRAYS WITH REPEAT AND TILE

In [141]:
# Repeat elements
repeat_array = np.repeat([1, 2, 3], 3)
print("Repeat [1,2,3] 3 times:", repeat_array)

# Tile arrays
tile_array = np.tile([1, 2], 3)
print("Tile [1,2] 3 times:", tile_array)

Repeat [1,2,3] 3 times: [1 1 1 2 2 2 3 3 3]
Tile [1,2] 3 times: [1 2 1 2 1 2]


# 9. CREATING ARRAYS WITH FROMFUNCTION

In [142]:
def create_value(i, j):
    return i + j


func_array = np.fromfunction(create_value, (2, 4))
func_array

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.]])

# 10. PRACTICAL EXAMPLES

In [143]:
# Example 1: Creating a feature matrix for ML
features = np.random.randn(100, 5)  # 100 samples, 5 features
print("Feature matrix shape:", features.shape)

# Example 2: Creating a time series
time_points = np.linspace(0, 10, 100)
signal = np.sin(time_points)
print("Time series length:", len(signal))

# Example 3: Creating a mask for image processing
image_mask = np.zeros((10, 10), dtype=bool)
image_mask[2:8, 2:8] = True
print("Image mask:\n", image_mask)

Feature matrix shape: (100, 5)
Time series length: 100
Image mask:
 [[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False  True  True  True  True  True  True False False]
 [False False  True  True  True  True  True  True False False]
 [False False  True  True  True  True  True  True False False]
 [False False  True  True  True  True  True  True False False]
 [False False  True  True  True  True  True  True False False]
 [False False  True  True  True  True  True  True False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]



# Key Takeaways
✓ np.array() converts Python lists to NumPy arrays . 

✓ Specify dtype for memory efficiency and precision

✓ Use built-in functions (zeros, ones, empty) for common patterns

✓ arange() and linspace() create sequences efficiently

✓ Random arrays are essential for simulations and ML

✓ Choose the right method based on your specific needs

# =============================================================================
# EXERCISES
# =============================================================================

1. Create a 5x5 identity matrix
2. Create an array of 20 evenly spaced numbers from 0 to 1
3. Create a 3x3 array filled with random integers from 1 to 10
4. Create a 2D array representing a 5x5 grid with values i+j
5. Create an array of 100 random normal numbers with mean=0, std=1
