# SECTION 3: ARRAY ATTRIBUTES AND PROPERTIES

In [64]:
import numpy as np

In [65]:
# Create a sample array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:\n", arr_2d)

# Basic attributes
print("Shape:", arr_2d.shape)
print("Size (total elements):", arr_2d.size)
print("Data type:", arr_2d.dtype)
print("Number of dimensions:", arr_2d.ndim)
print("Memory usage (bytes):", arr_2d.nbytes)
print("Item size (bytes per element):", arr_2d.itemsize)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size (total elements): 9
Data type: int64
Number of dimensions: 2
Memory usage (bytes): 72
Item size (bytes per element): 8


In [66]:
# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array:", arr_1d)
print("Shape:", arr_1d.shape)
print("Dimensions:", arr_1d.ndim)

1D array: [1 2 3 4 5]
Shape: (5,)
Dimensions: 1


In [67]:
# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D array:\n", arr_2d)
print("Shape:", arr_2d.shape)
print("Dimensions:", arr_2d.ndim)


2D array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2


In [68]:
# 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D array:\n", arr_3d)
print("Shape:", arr_3d.shape)
print("Dimensions:", arr_3d.ndim)


3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions: 3


In [69]:
# Different data types
int_array = np.array([1, 2, 3], dtype=np.int32)

print("Integer array:", int_array)
print("Data type:", int_array.dtype)
print("Memory usage:", int_array.nbytes, "bytes")


Integer array: [1 2 3]
Data type: int32
Memory usage: 12 bytes


In [70]:
float_array = np.array([1.1, 2.2, 3.3], dtype=np.float64)
print("\nFloat array:", float_array)
print("Data type:", float_array.dtype)
print("Memory usage:", float_array.nbytes, "bytes")


Float array: [1.1 2.2 3.3]
Data type: float64
Memory usage: 24 bytes


In [71]:
bool_array = np.array([True, False, True], dtype=np.bool_)

print("\nBoolean array:", bool_array)
print("Data type:", bool_array.dtype)
print("Memory usage:", bool_array.nbytes, "bytes")


Boolean array: [ True False  True]
Data type: bool
Memory usage: 3 bytes


In [72]:
string_array = np.array(["a", "b", "c"], dtype=np.str_)

print("\nString array:", string_array)
print("Data type:", string_array.dtype)
print("Memory usage:", string_array.nbytes, "bytes")


String array: ['a' 'b' 'c']
Data type: <U1
Memory usage: 12 bytes


 Memory layout attributes

In [73]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Flags:", arr.flags)
print("C-contiguous:", arr.flags["C_CONTIGUOUS"])
print("F-contiguous:", arr.flags["F_CONTIGUOUS"])
print("Memory layout:", arr.flags["F_CONTIGUOUS"] and "F" or "C")

Array:
 [[1 2 3]
 [4 5 6]]
Flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

C-contiguous: True
F-contiguous: False
Memory layout: C


 Memory efficiency comparison

In [74]:
large_array_int32 = np.zeros((1000, 1000), dtype=np.int32)
large_array_int64 = np.zeros((1000, 1000), dtype=np.int64)
large_array_float32 = np.zeros((1000, 1000), dtype=np.float32)
large_array_float64 = np.zeros((1000, 1000), dtype=np.float64)

print(f"\nMemory usage comparison for 1000x1000 arrays:")
print(f"int32: {large_array_int32.nbytes:,} bytes")
print(f"int64: {large_array_int64.nbytes:,} bytes")
print(f"float32: {large_array_float32.nbytes:,} bytes")
print(f"float64: {large_array_float64.nbytes:,} bytes")


Memory usage comparison for 1000x1000 arrays:
int32: 4,000,000 bytes
int64: 8,000,000 bytes
float32: 4,000,000 bytes
float64: 8,000,000 bytes


In [75]:
arr_positive = np.array([1, 2, 3, 4, 5])
print("Array:", arr_positive)
print("All positive:", np.all(arr_positive > 0))
print("Any positive:", np.any(arr_positive > 0))
print("All finite:", np.all(np.isfinite(arr_positive)))

Array: [1 2 3 4 5]
All positive: True
Any positive: True
All finite: True


In [76]:
arr_mixed = np.array([-1, 0, 1, -2, 3])

print("Array:", arr_mixed)
print("All positive:", np.all(arr_positive > 0))
print("Any positive:", np.any(arr_positive > 0))
print("All finite:", np.all(np.isfinite(arr_positive)))

Array: [-1  0  1 -2  3]
All positive: True
Any positive: True
All finite: True


In [77]:
arr_zeros = np.array([0, 0, 0, 0, 0])

print("Array:", arr_zeros)
print("All zero:", np.all(arr_zeros == 0))
print("Any zero:", np.any(arr_zeros == 0))

Array: [0 0 0 0 0]
All zero: True
Any zero: True


In [78]:
# NumPy arrays don't have a built-in metadata attribute
# We can create a custom class to store metadata alongside the array
class ArrayWithMetadata:
    def __init__(self, array, metadata=None):
        self.array = array
        self.metadata = metadata or {}

arr_data = np.array([1, 2, 3, 4, 5])
metadata = {"description": "Sample array", "units": "meters"}
arr_with_metadata = ArrayWithMetadata(arr_data, metadata)

print("Array:", arr_with_metadata.array)
print("Metadata:", arr_with_metadata.metadata)

Array: [1 2 3 4 5]
Metadata: {'description': 'Sample array', 'units': 'meters'}


# ARRAY VIEWS AND COPIES

In [79]:
original = np.array([1, 2, 3, 4, 5])
print("Original:", original)
print("Base:", original.base)  # None for original array

Original: [1 2 3 4 5]
Base: None


In [80]:
view = original[1:4]
print("\nView:", view)
print("View base:", view.base)  # Points to original
print("View is original:", view.base is original)


View: [2 3 4]
View base: [1 2 3 4 5]
View is original: True


In [81]:
copy = original[1:4].copy()
print("\nCopy:", copy)
print("Copy base:", copy.base)  # None for copy
print("Copy is original:", copy.base is original)


Copy: [2 3 4]
Copy base: None
Copy is original: False


# ARRAY FLAGS AND LAYOUT

In [82]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Flags:")
print("  C_CONTIGUOUS:", arr.flags["C_CONTIGUOUS"])
print("  F_CONTIGUOUS:", arr.flags["F_CONTIGUOUS"])
print("  OWNDATA:", arr.flags["OWNDATA"])
print("  WRITEABLE:", arr.flags["WRITEABLE"])
print("  ALIGNED:", arr.flags["ALIGNED"])

Array:
 [[1 2 3]
 [4 5 6]]
Flags:
  C_CONTIGUOUS: True
  F_CONTIGUOUS: False
  OWNDATA: True
  WRITEABLE: True
  ALIGNED: True


# Example 1: Memory-efficient data processing

In [83]:
large_dataset = np.random.randn(10000, 100)
print(f"Dataset shape: {large_dataset.shape}")
print(f"Memory usage: {large_dataset.nbytes:,} bytes")
print(f"Data type: {large_dataset.dtype}")

Dataset shape: (10000, 100)
Memory usage: 8,000,000 bytes
Data type: float64


In [84]:
# Convert to smaller data type for memory efficiency
large_dataset_float32 = large_dataset.astype(np.float32)
print(f"After conversion to float32: {large_dataset_float32.nbytes:,} bytes")
print(f"Memory saved: {large_dataset.nbytes - large_dataset_float32.nbytes:,} bytes")

After conversion to float32: 4,000,000 bytes
Memory saved: 4,000,000 bytes


# Example 2: Array validation

In [85]:
def validate_array(arr):
    print(f"Array shape: {arr.shape}")
    print(f"Data type: {arr.dtype}")
    print(f"Memory usage: {arr.nbytes:,} bytes")
    print(f"Has NaN: {np.any(np.isnan(arr))}")
    print(f"Has infinite values: {np.any(np.isinf(arr))}")
    print(f"Is contiguous: {arr.flags['C_CONTIGUOUS']}")


sample_array = np.array([1, 2, 3, np.nan, 5])
validate_array(sample_array)

Array shape: (5,)
Data type: float64
Memory usage: 40 bytes
Has NaN: True
Has infinite values: False
Is contiguous: True


# Example 3: Performance considerations

In [86]:
# Create arrays with different memory layouts
arr_c = np.array([[1, 2, 3], [4, 5, 6]], order="C")  # C-contiguous
arr_f = np.array([[1, 2, 3], [4, 5, 6]], order="F")  # F-contiguous
# the difference between the two is that the C-contiguous array is stored in a row-major order, 
# while the F-contiguous array is stored in a column-major order.
print("C-contiguous array:")
print("  Flags:", arr_c.flags)
print("  Layout:", "C" if arr_c.flags["C_CONTIGUOUS"] else "F")

print("F-contiguous array:")
print("  Flags:", arr_f.flags)
print("  Layout:", "C" if arr_f.flags["C_CONTIGUOUS"] else "F")

C-contiguous array:
  Flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

  Layout: C
F-contiguous array:
  Flags:   C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

  Layout: F
