In [2]:
import numpy as np

In [3]:
# Create a sample array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Original array:\n", arr)

# Basic indexing
print("Element at [0, 1]:", arr[0, 1])
print("Element at [2, 3]:", arr[2, 3])

# Negative indexing
print("Element at [-1, -1]:", arr[-1, -1])
print("Element at [-2, -3]:", arr[-2, -3])

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at [0, 1]: 2
Element at [2, 3]: 12
Element at [-1, -1]: 12
Element at [-2, -3]: 6


In [4]:
# 1D array slicing
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("1D array:", arr_1d)
print("First 3 elements:", arr_1d[:3])
print("Last 3 elements:", arr_1d[-3:])
print("Every 2nd element:", arr_1d[::2])
print("Reverse array:", arr_1d[::-1])

# 2D array slicing
print("\n2D array:\n", arr)
print("First row:", arr[0])
print("First column:", arr[:, 0])
print("Last row:", arr[-1])
print("Last column:", arr[:, -1])

1D array: [1 2 3 4 5 6 7 8]
First 3 elements: [1 2 3]
Last 3 elements: [6 7 8]
Every 2nd element: [1 3 5 7]
Reverse array: [8 7 6 5 4 3 2 1]

2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
First column: [1 5 9]
Last row: [ 9 10 11 12]
Last column: [ 4  8 12]


In [5]:
# Multiple slices
print("First two rows:\n", arr[:2])
print("Last two columns:\n", arr[:, -2:])
print("Subarray [1:3, 1:3]:\n", arr[1:3, 1:3])

# Step slicing
print("Every other row:\n", arr[::2])
print("Every other column:\n", arr[:, ::2])
print("Every other element in both dimensions:\n", arr[::2, ::2])

First two rows:
 [[1 2 3 4]
 [5 6 7 8]]
Last two columns:
 [[ 3  4]
 [ 7  8]
 [11 12]]
Subarray [1:3, 1:3]:
 [[ 6  7]
 [10 11]]
Every other row:
 [[ 1  2  3  4]
 [ 9 10 11 12]]
Every other column:
 [[ 1  3]
 [ 5  7]
 [ 9 11]]
Every other element in both dimensions:
 [[ 1  3]
 [ 9 11]]


In [6]:
# Create boolean mask
mask = arr > 5
print("Boolean mask:\n", mask)
print("Elements > 5:", arr[mask])

# Multiple conditions
mask_even = arr % 2 == 0
print("Even elements:", arr[mask_even])

# Combined conditions
mask_combined = (arr > 5) & (arr < 10)
print("Elements between 5 and 10:", arr[mask_combined])

Boolean mask:
 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
Elements > 5: [ 6  7  8  9 10 11 12]
Even elements: [ 2  4  6  8 10 12]
Elements between 5 and 10: [6 7 8 9]


In [7]:
# Integer array indexing
indices = np.array([0, 2])
print("Using integer array indexing:", arr[indices])

# Multiple index arrays
row_indices = np.array([0, 2])
col_indices = np.array([1, 3])
print("Fancy indexing [0, 2], [1, 3]:", arr[row_indices, col_indices])

Using integer array indexing: [[ 1  2  3  4]
 [ 9 10 11 12]]
Fancy indexing [0, 2], [1, 3]: [ 2 12]


In [8]:
# Create a 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D array:\n", arr_3d)
print("Shape:", arr_3d.shape)

# Indexing in 3D
print("Element at [0, 1, 0]:", arr_3d[0, 1, 0])
print("First 2D slice:\n", arr_3d[0])
print("First row of first 2D slice:", arr_3d[0, 0])

3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Element at [0, 1, 0]: 3
First 2D slice:
 [[1 2]
 [3 4]]
First row of first 2D slice: [1 2]


In [9]:
# Create original array
original = np.array([1, 2, 3, 4, 5])
print("Original:", original)

# View (no copy)
view = original[1:4]
print("View:", view)
view[0] = 999
print("After modifying view - Original:", original)
print("After modifying view - View:", view)

# Copy
original = np.array([1, 2, 3, 4, 5])
copy = original[1:4].copy()
print("\nCopy:", copy)
copy[0] = 999
print("After modifying copy - Original:", original)
print("After modifying copy - Copy:", copy)

Original: [1 2 3 4 5]
View: [2 3 4]
After modifying view - Original: [  1 999   3   4   5]
After modifying view - View: [999   3   4]

Copy: [2 3 4]
After modifying copy - Original: [1 2 3 4 5]
After modifying copy - Copy: [999   3   4]


In [10]:
# Create a 4D array
arr_4d = np.random.randn(2, 3, 4, 5)
print("4D array shape:", arr_4d.shape)

4D array shape: (2, 3, 4, 5)


In [11]:
# Using ellipsis
print("First element of each 3D slice:", arr_4d[0, ..., 0])
print("Last element of each 3D slice:", arr_4d[-1, ..., -1])

First element of each 3D slice: [[ 0.24987848  0.42443327 -0.05002462 -0.35135772]
 [ 1.20961517  1.07245071  0.91709359  0.10104538]
 [ 0.92428827  0.42661883  0.72542831 -0.06231494]]
Last element of each 3D slice: [[ 1.03010637 -0.23287646  0.54003083 -1.41057658]
 [-1.4449882  -1.06575491  0.45636459 -0.20285843]
 [-0.60365854 -1.0551453   0.30944174  0.70773091]]


In [12]:
# Example 1: Image processing simulation
print("Example 1: Image processing simulation")
image = np.random.randint(0, 256, (10, 10))
print("Original image shape:", image.shape)
print("Image center (3x3):\n", image[3:6, 3:6])

Example 1: Image processing simulation
Original image shape: (10, 10)
Image center (3x3):
 [[ 43 102  60]
 [195 167  38]
 [ 71 195 197]]


In [13]:
# Extract border
border = np.zeros_like(image)
border[0, :] = image[0, :]  # Top border
border[-1, :] = image[-1, :]  # Bottom border
border[:, 0] = image[:, 0]  # Left border
border[:, -1] = image[:, -1]  # Right border
print("Image border:\n", border)

Image border:
 [[191 183 217  71 241 187  85 102 131   6]
 [100   0   0   0   0   0   0   0   0   1]
 [192   0   0   0   0   0   0   0   0   6]
 [165   0   0   0   0   0   0   0   0 220]
 [ 75   0   0   0   0   0   0   0   0 248]
 [ 26   0   0   0   0   0   0   0   0 155]
 [141   0   0   0   0   0   0   0   0  85]
 [166   0   0   0   0   0   0   0   0 249]
 [ 96   0   0   0   0   0   0   0   0  34]
 [ 63 131  92 137 254 243 122  65 227  85]]


In [14]:
# Example 2: Data filtering
print("\nExample 2: Data filtering")
data = np.random.randn(100)
print("Data shape:", data.shape)
print("Data range:", data.min(), "to", data.max())


Example 2: Data filtering
Data shape: (100,)
Data range: -2.4613256138411823 to 2.430449681840738


In [16]:
# Filter outliers (values beyond 2 standard deviations)
mean_val = np.mean(data)
std_val = np.std(data)
outlier_mask = (data < mean_val - 2 * std_val) | (data > mean_val + 2 * std_val)
filtered_data = data[~outlier_mask]
print("mean:",mean_val)
print("std:",std_val)
print("Outlier mask:", outlier_mask)
print("Filtered data:", filtered_data)
print("Original data size:", len(data))
print("Filtered data size:", len(filtered_data))
print("Outliers removed:", len(data) - len(filtered_data))

mean: 0.21212144687252493
std: 0.9461823131782953
Outlier mask: [False False False False False False False False False  True False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False  True
 False False False False False False False False False False False False
 False False False False False False False False False False False  True
 False False False False False False False False False False False False
 False False False False False False False False False False False  True
 False False False False]
Filtered data: [ 0.88995562  0.92127646 -0.64258537 -0.41423294 -0.18475584 -0.91069839
 -0.92217393  1.35647246  0.80138213 -0.02381492  1.70845771  0.69524024
 -0.05291705 -0.448735    1.05116457  1.90254008  0.64376512  1.00014654
  0.37897483 -0.09316992 -0.57374871  0.83009533 -0.14584842  0.4033685
  0.20544342  0.4263

In [17]:
# Example 3: Matrix operations
print("\nExample 3: Matrix operations")
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Original matrix:\n", matrix)

# Extract diagonal elements
diagonal = matrix[np.arange(min(matrix.shape)), np.arange(min(matrix.shape))]
print("Diagonal elements:", diagonal)

# Extract upper triangular elements
upper_tri = matrix[np.triu_indices_from(matrix)]
print("Upper triangular elements:", upper_tri)


Example 3: Matrix operations
Original matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Diagonal elements: [ 1  6 11]
Upper triangular elements: [ 1  2  3  4  6  7  8 11 12]


In [18]:
# Pattern 1: Selecting specific rows/columns
print("Pattern 1: Selecting specific rows/columns")
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Original:\n", arr)
print("Rows 0 and 2:\n", arr[[0, 2]])
print("Columns 1 and 3:\n", arr[:, [1, 3]])

# Pattern 2: Conditional selection
print("\nPattern 2: Conditional selection")
print("Elements > 6:", arr[arr > 6])
print("Even elements:", arr[arr % 2 == 0])

# Pattern 3: Reversing arrays
print("\nPattern 3: Reversing arrays")
print("Reversed rows:\n", arr[::-1])
print("Reversed columns:\n", arr[:, ::-1])

Pattern 1: Selecting specific rows/columns
Original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Rows 0 and 2:
 [[ 1  2  3  4]
 [ 9 10 11 12]]
Columns 1 and 3:
 [[ 2  4]
 [ 6  8]
 [10 12]]

Pattern 2: Conditional selection
Elements > 6: [ 7  8  9 10 11 12]
Even elements: [ 2  4  6  8 10 12]

Pattern 3: Reversing arrays
Reversed rows:
 [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
Reversed columns:
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
