In [2]:
import numpy as np

In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Matrix A:\n", A)
print("Matrix B:\n", B)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]


In [4]:
print("Matrix multiplication:\n", np.dot(A, B))
print("Element-wise multiplication:\n", A * B)
print("Transpose of A:\n", A.T)
print("Determinant of A:", np.linalg.det(A))
print("Inverse of A:\n", np.linalg.inv(A))
print("Eigenvalues of A:", np.linalg.eigvals(A))

Matrix multiplication:
 [[19 22]
 [43 50]]
Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Transpose of A:
 [[1 3]
 [2 4]]
Determinant of A: -2.0000000000000004
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues of A: [-0.37228132  5.37228132]


In [ ]:
# Solving linear equations: Ax = b
b = np.array([5, 6])
x = np.linalg.solve(A, b)
("Solution to Ax = b:", x)

Solution to Ax = b: [-4.   4.5]
