In [2]:
import numpy as np

Set seed for reproducibility

In [3]:
np.random.seed(42)

### Different types of random numbers

In [4]:
print("Random integers (1-10):", np.random.randint(1, 11, 5))
print("Random floats (0-1):", np.random.random(5))
print("Random normal distribution:", np.random.normal(0, 1, 5))
print("Random uniform distribution:", np.random.uniform(0, 10, 5))

Random integers (1-10): [7 4 8 5 7]
Random floats (0-1): [0.44583275 0.09997492 0.45924889 0.33370861 0.14286682]
Random normal distribution: [-0.4826188   0.16416482  0.23309524  0.11799461  1.46237812]
Random uniform distribution: [0.07066305 0.23062425 5.2477466  3.99860972 0.46665663]


# Random choice and shuffle

In [ ]:
# Random choice 
choices = np.array(["A", "B", "C", "D"])
print("Random choice:", np.random.choice(choices, 3))
print("Random choice with replacement:", np.random.choice(choices, 3, replace=True))

Random choice: ['D' 'D' 'C']
Random choice with replacement: ['B' 'B' 'C']


In [ ]:
# Random shuffle
arr = np.array([[0, 0, 0, 0, 0], [1, 1, 1, 1, 1]])
print("Original array:\n", arr)
np.random.shuffle(arr)
print("Shuffled array:\n", arr)


Original array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shuffled array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
