In [3]:
import numpy as np

In [4]:
arr_1d = np.arange(12)
arr_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Reshaping

In [6]:
arr_2d = arr_1d.reshape(3, 4)
print("Reshaped to (3, 4):\n", arr_2d)
arr_3d = arr_1d.reshape(2, 3, 2)
print("Reshaped to (2, 3, 2):\n", arr_3d)

Reshaped to (3, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to (2, 3, 2):
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [7]:
# Flattening
print("Flattened:", arr_2d.flatten())
print("Ravel (flatten):", arr_2d.ravel())

Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravel (flatten): [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [8]:
# Transposing
print("Transposed:\n", arr_2d.T)

Transposed:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
# Concatenation
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Concatenated:", np.concatenate([arr1, arr2]))
print("Stacked vertically:\n", np.vstack([arr1, arr2]))
print("Stacked horizontally:", np.hstack([arr1, arr2]))