In [12]:
import numpy as np

In [13]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Original array:\n", arr)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Integer array indexing

In [14]:
indices = np.array([0, 2])
print("Using integer array indexing: \n", arr[indices])

Using integer array indexing: 
 [[ 1  2  3  4]
 [ 9 10 11 12]]


# Boolean array indexing

In [15]:
mask = arr > 5
print("Boolean mask:\n", mask)
print("Elements > 5:", arr[mask])

Boolean mask:
 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
Elements > 5: [ 6  7  8  9 10 11 12]


# Fancy indexing

In [ ]:
print("Fancy indexing [0, 2]:\n", arr[[0, 2]])
print("Fancy indexing [0, 2], [1, 3]:\n", arr[[0, 2], [1, 3]])

Fancy indexing [0, 2]: [[ 1  2  3  4]
 [ 9 10 11 12]]
Fancy indexing [0, 2], [1, 3]: [ 2 12]
