# SECTION 11: MEMORY EFFICIENCY AND VIEWS VS COPIES


In [1]:
import numpy as np

In [2]:
original = np.array([1, 2, 3, 4, 5])
original

array([1, 2, 3, 4, 5])

# View (no copy)


In [ ]:
view = original[1:4]
print("View: \n", view)
view[0] = 999
print("before modifying view - Original: \n", original)
print("After modifying view - View: \n", view)

View: 
 [2 3 4]
After modifying view - Original: 
 [  1 999   3   4   5]
After modifying view - View: 
 [999   3   4]


# copy

In [ ]:
copy = original[1:4].copy()
print("Copy:", copy)
copy[0] = 999
print("After modifying copy - Original:", original)
print("After modifying copy - Copy:", copy)